services:
  jwt-db:
    image: postgres:16.4
    container_name: jwt-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: JWT
    ports:
      - "5439:5432"
    volumes:
      - jwt-db-data:/var/lib/postgresql/data

volumes:
  jwt-db-data: